title: postman
description: 1.12.2 anarchy client :)
logo: /src/main/resources/postmancircle.png
show_downloads: true
github:
  repository_url: https://github.com/moomooooo/postman
  discord_url: https://discord.gg/Jd8EmEuhb5
  jar_url: https://github.com/moomooooo/postman/releases/download/1.203/postman1.203.jar
cur_ver: 1.203
theme: jekyll-theme-cayman
