title: postman
description: 1.12.2 anarchy client :)
show_downloads: true
github:
  repository_url: https://github.com/moomooooo/postman
  website_url: https://moomooooo.github.io/postman/
  jar_url: https://github.com/moomooooo/postman/releases/download/1.200/postman1.200.jar
cur_ver: 1.200
discord_url: https://discord.gg/Jd8EmEuhb5
theme: jekyll-theme-minimal
